### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by VodkaMan69** [ergrelet/unlicense#133] opened 2024-09-07 18:28 UTC
Don't download it is a virus
FUCK YOU HACKER

**Comment by alexrp** [comment] 2024-09-07 19:38
Anti-virus software falsely flagging a reverse engineering tool? Say it ain't so. :disappointed:

**Comment by VodkaMan69** [comment] 2024-09-07 20:03
> Anti-virus software falsely flagging a reverse engineering tool? Say it ain't so. 😞

Bro literally after I opened the unpacked exe the browser opened pornhub and when ever I try to download malware bytes it would close the browser and when I finally downloaded malwarebytes and tried to install it a voice said hello world so wtf are you talking about?

**Comment by alexrp** [comment] 2024-09-07 20:18
Sounds to me like the original executable was malicious. Unpacking it with Unlicense is not going to change that; the resulting unpacked executable will be just as malicious. This is why you should do stuff like this in a VM at a bare minimum if you're working with an executable that's potentially malicious.

Unlicense is not at fault here. In fact, the README explicitly states:

> Warning: This tool will execute the target executable. Make sure to use this tool in a VM if you're unsure about what the target executable does.

**Comment by VodkaMan69** [comment] 2024-09-07 23:37
> Sounds to me like the original executable was malicious. Unpacking it with Unlicense is not going to change that; the resulting unpacked executable will be just as malicious. This is why you should do stuff like this in a VM at a bare minimum if you're working with an executable that's potentially malicious.
> 
> Unlicense is not at fault here. In fact, the README explicitly states:
> 
> > Warning: This tool will execute the target executable. Make sure to use this tool in a VM if you're unsure about what the target executable does.

bro the original excutable had no notes in the 64db that says hello world but the unpacked did 💀

**Comment by alexrp** [comment] 2024-09-07 23:51
Yes, because it was packed. Making it harder to discover information like strings in an executable is one of the major reasons to use executable packers.

**Comment by VodkaMan69** [comment] 2024-09-08 01:14
> Yes, because it was packed. Making it harder to discover information like strings in an executable is one of the major reasons to use executable packers.

nah the actual exe didn't do this and is secure

**Comment by alexrp** [comment] 2024-09-08 01:27
I really don't know what to tell you then. The source code for Unlicense is right here in this repository, open for anyone to view, and people ([including myself](https://www.alexrp.com/p/unpacking-and-repairing-the-tera-executable)) have used it successfully. If you believe Unlicense is malicious, all you need to do is point to the malicious code.

**Comment by ergrelet** [comment] 2024-09-08 17:58
Hi,

As @alexrp mentioned, the README explicitly states to be careful when unpacking unknown executables, specifically because Themida and other packers are regularly used to protect malware.
Unlicense's release artifacts have been downloaded thousands of times and you are the only one witnessing a malicious behavior, so it seems pretty safe to assume this behavior is not the cause of unlicense itself. The source code is obviously also freely accessible to verify that claim, as @alexrp also pointed out.

So I'll close this issue as it's pure defamation.

**Closed as completed by ergrelet** 2024-09-08 17:58 UTC
